[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
chrono = {version = "0.4.24", features = ["serde"]}
serde = {version = "1.0.159", features =["derive"]}
serde_derive = "1.0"
anyhow = "1.0"
tokio = { version = "1.28.0", features = ["full"] }
scylla = "0.8.1"
futures = "0.3.6"
uuid = "1.0"
bigdecimal = "0.2.0"
num-bigint = "0.3"
tracing = "0.1.25"
tracing-subscriber = {version="0.3.14", features=["env-filter"]}
